model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan_seq.VQSEQModel
  params:
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 512
      in_channels: 3
      out_ch: 3
      ch: 64
      ch_mult: [1,1,2,2,4,8]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithSeqDiscriminator
      params:
        disc_conditional: False
        D_type: seq
        disc_in_channels: 12
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 8
    train:
      target: taming.data.lrw.LRWTrain
      params:
        training_images_list_file: configs/talking_config/lrw_train.yaml
        size: 256
    validation:
      target: taming.data.lrw.LRWTest
      params:
        test_images_list_file: configs/talking_config/lrw_val.yaml
        size: 256

